name=input('What is your name? ')
gpa=float(input('What is your GPA? '))
c_h=int(input('How many your credit hours are? '))
print(f"Student's name: {name}")
print(gpa >= 3.5 and c_h >= 12)
if gpa < 3.5: print(f"{3.5-gpa} more GPA points needed.")
else: print(' ')
if c_h < 12: print(f"{12-c_h} more credits needed.")
else: print(' ')
